# Prometheus configuration for SIEM Lite monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "rules/*.yml"

# Scrape configuration
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # SIEM Lite application
  - job_name: 'siem-lite'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # SIEM Lite health checks
  - job_name: 'siem-lite-health'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/api/health'
    scrape_interval: 30s
    
  # Node exporter for system metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    
  # Redis metrics (if available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
